### ISSUE TITLE
show_mapping command error in 0.4.1 and django 1.10.4

### ISSUE THREAD

**Issue by Visgean** [bennylope/elasticstack#23]
```
$ ./manage.py show_mapping                                                                                                                                     Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/home/visgean/.virtualenvs/seeder/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/visgean/.virtualenvs/seeder/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/visgean/.virtualenvs/seeder/lib/python3.5/site-packages/django/core/management/__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/home/visgean/.virtualenvs/seeder/lib/python3.5/site-packages/django/core/management/__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/home/visgean/.virtualenvs/seeder/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/visgean/.virtualenvs/seeder/lib/python3.5/site-packages/elasticstack/management/commands/show_mapping.py", line 34, in <module>
    class Command(BaseCommand):
  File "/home/visgean/.virtualenvs/seeder/lib/python3.5/site-packages/elasticstack/management/commands/show_mapping.py", line 39, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

**Comment by bennylope** [comment]
Thank you for reporting this - `0.5.0` is up on PyPI now.

**Comment by Visgean** [comment]
Thanks for the fix :).
